version: '3'
services:
  spring-boot-mongodb:
    container_name: spring-boot-mongodb-container
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
    image: docker-spring-boot-mongodb
    ports:
      - "1042:1042"
      - "1045:1045"
    networks:
      - spring-boot-mongodb-net

  mongodb:
    container_name: mongodb
    image: mongo:3.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gautam
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - spring-boot-mongodb-net

networks:
  spring-boot-mongodb-net: