apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo:3.6
        name: mongo
        args:
          - --auth
        env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "role=mongo,environment=test"
          - name: MONGODB_USERNAME
            value: gautam
          - name: MONGODB_PASSWORD
            value: password
          - name: MONGODB_DATABASE
            value: admin
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-persistent-storage
          hostPath:
                path: /data/storage/mongodb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: springboot-docker
spec: 
  replicas: 2
  template: 
    metadata: 
      labels: 
        app: springboot-docker
    spec: 
      containers: 
        - image: pura1029/docker-spring-boot-mongodb:latest
          name: springboot-docker
          ports: 
          - containerPort: 1042
          - containerPort: 1045
          env:
          - name: mongo_uri
            value: mongo-service
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-docker
  labels:
      app: springboot-docker
spec:
  ports:
    - name: http
      port: 1042
      targetPort: 1042
    - name: https
      port: 1045
      targetPort: 1045
  selector:
    app: springboot-docker
  type: NodePort