apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-service-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: spring-boot-service
    spec:
      containers:
      - name: spring-boot-service
        image: pura1029/docker-spring-boot-mongodb
        ports:
        - containerPort: 1042
        - containerPort: 1045
        env:
        - name: mongo_uri
          value: mongodb-service