apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc128gb
 annotations:
  volume.beta.Kubernetes.io/storage-class: "platinum"
spec:
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 128Gi