apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo:3.6
        name: mongo
        args:
          - --auth
        env:
          - name: MONGODB_USERNAME
            value: gautam
          - name: MONGODB_PASSWORD
            value: password
          - name: MONGODB_ROOT_USERNAME
            value: gautam
          - name: MONGODB_ROOT_PASSWORD
            value: password
          - name: MONGODB_DATABASE
            value: admin
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-persistent-storage
          hostPath:
                path: /data/storage/mongodb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo