version: '3'
services:
  spring-boot-mongodb:
    container_name: boot-mongodb-producer-container
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
    image: pura1029/boot-mongodb-producer
    ports:
      - "30082:30082"
      - "1035:1035"
    networks:
      - spring-boot-mongodb-net

  mongodb:
    container_name: mongo-service
    image: mongo:3.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gautam
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - spring-boot-mongodb-net

networks:
  spring-boot-mongodb-net: