version: '3'
services:
  spring-boot-mongodb-consumer:
    container_name: boot-mongodb-consumer-container
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
    image: pura1029/boot-mongodb-consumer
    ports:
      - "1036:1036"
      - "30084:30084"
    networks:
      - spring-boot-mongodb-net

  mongodb:
    container_name: mongo-service
    image: mongo:3.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gautam
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - spring-boot-mongodb-net

networks:
  spring-boot-mongodb-net: